In [1]:
import tensorflow as tf

In [4]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [5]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [6]:
print(tf.reduce_sum(tf.random.normal([1000,1000])))

tf.Tensor(401.05988, shape=(), dtype=float32)


#### Tensorflow 2.10.0 시작하기

In [7]:
# Hello world 
# 텐서플로는  C++와 python을 기반으로 한다. Google Colab도 python을 기본적으로 지원하고 있다.
print("Hello, world!")

Hello, world!


 텐서플로는 GitHub에 공개된 open source library로서 약 75,000개의 fork가 만들어지고 2,100여명의 코드 기여자가 있으며, 거의 매 주마다 마이너 버전이 업데이트된다. Library의 version정보가 다르면 잘 돌아가야 할 코드에서 에러가 발생할 수도 있다. 설치한 텐서플로의 버전을 확인해 보자.

In [9]:
print(tf.__version__)

2.10.0


##### perceptron의 한계를 지적하는데 사용됐던 AND, OR, XOR 연산을 할 수 있는 신경망 네트워크를 만들어보자

In [29]:
# [0,1] 구간의 uniform distribution에서 shape=(1,)인 난수 생성
rand = tf.random.uniform([1], 0, 1)
print(rand)

tf.Tensor([0.17867386], shape=(1,), dtype=float32)


In [32]:
# [0,1] 구간의 uniform distribution에서 shape=(4,)인 난수 생성
rand = tf.random.uniform(shape=[4], minval=0, maxval=1)
print(rand)

tf.Tensor([0.20703745 0.8988174  0.37414896 0.82971346], shape=(4,), dtype=float32)


In [31]:
# 평균이 0, 표준편차가 1 인 정규분포에서 shape=(3,2)인 난수 행렬 생성
rand = tf.random.normal(shape=[3,2], mean=0, stddev=1)
print(rand)

tf.Tensor(
[[-0.81094915  0.4870714 ]
 [-1.6467528  -1.3862404 ]
 [-1.4208333  -2.8433623 ]], shape=(3, 2), dtype=float32)
