##### 데이터프레임 인덱스 조작

In [1]:
import numpy as np
import pandas as pd

##### 인덱스 설정 및 제거

In [2]:
list('ABCD')

['A', 'B', 'C', 'D']

In [17]:
# random.randint(low, high=None, size=None, dtype=int)
np.random.seed(123)

low, high = 3, 10

sample_10 = np.random.randint(low=low, high=high, size=10)
print(sample_10)

[9 8 9 5 7 5 9 4 6 5]


In [21]:
# random.randn(d0, d1, ..., dn) : standard normal dist에서 원하는 차원의 난수들을 생성
sample_2_5 = np.random.randn(2,5)
print(sample_2_5)
print(np.round(sample_2_5, 2))

[[-1.10098526 -1.4103012  -0.74765132 -0.98486761 -0.74856868]
 [ 0.24036728 -1.85563747 -1.7794548  -2.75022426 -0.23415755]]
[[-1.1  -1.41 -0.75 -0.98 -0.75]
 [ 0.24 -1.86 -1.78 -2.75 -0.23]]


In [22]:
# random.rand(d0, d1, ..., dn) : [0, 1)구간의 uniform dist에서 원하는 차원의 난수들을 생성
sample_3_5 = np.random.rand(3,5)
print(sample_3_5)
print(np.round(sample_3_5, 2))

[[0.31226122 0.42635131 0.89338916 0.94416002 0.50183668]
 [0.62395295 0.1156184  0.31728548 0.41482621 0.86630916]
 [0.25045537 0.48303426 0.98555979 0.51948512 0.61289453]]
[[0.31 0.43 0.89 0.94 0.5 ]
 [0.62 0.12 0.32 0.41 0.87]
 [0.25 0.48 0.99 0.52 0.61]]


In [25]:
# random.shuffle(x) : modify a sequence in-place by shuffling its contents
np.random.seed(123)
x = [2,9,1,0,8,6,3,7,5,4]
np.random.shuffle(x)
print(x)

[8, 2, 7, 6, 5, 0, 9, 3, 4, 1]


In [14]:
# random.choice(a, size=None, replace=True, p=None)
np.random.seed(123)

a = [2,6,0,12,20]
p = [0.2, 0.2, 0.15, 0.25, 0.2]

sample_3_no_repl = np.random.choice(a=a, size=4, replace=False, p=p)
print(sample_3_no_repl)

sample_8_repl = np.random.choice(a=a, size=9, replace=True, p=p)
print(sample_8_repl)

[12  6 20  0]
[20 12  0  6  6 12  0  2  6]


In [26]:
# random.permutation(x) : randomly permutes a sequence
np.random.seed(123)
x = [2,9,1,0,8,6,3,7,5,4]
perm_x = np.random.permutation(x)
print(perm_x)

[8 2 7 6 5 0 9 3 4 1]


##### np.random에는 np.random.noraml, standard_t, poisson, exponential, chisquare, uniform, ...등이 있다.