### Numerical Python(Numpy) - Part1

In [25]:
# de facto standard (사실상의 표준)
import numpy as np

In [26]:
a = [1,2,3]
a * 3, a + a + a

([1, 2, 3, 1, 2, 3, 1, 2, 3], [1, 2, 3, 1, 2, 3, 1, 2, 3])

In [27]:
list(map(lambda x : 3 * x, a))

[3, 6, 9]

### 1. Numpy Dimensional Array

In [28]:
tuple(map(lambda y : y / 5, a))

(0.2, 0.4, 0.6)

In [29]:
b = np.array(a)
b * 3

array([3, 6, 9])

##### 1.Numpy Dimensional Array

In [30]:
c = np.array(a, float)
c

array([1., 2., 3.])

In [31]:
type(c)

numpy.ndarray

In [32]:
c.dtype, c.shape

(dtype('float64'), (3,))

##### 2. Array Shape

In [33]:
# Vector(1차원)
vector = np.array([1,4,5,8])
vector_2dm = vector.reshape(-1, 4)

print(vector, vector_2dm)
vector.shape, vector_2dm.shape

[1 4 5 8] [[1 4 5 8]]


((4,), (1, 4))

In [34]:
# Matrix(2차원)
matrix = np.array([[1, 2, 3], [4, 15, 6]])
matrix

array([[ 1,  2,  3],
       [ 4, 15,  6]])

In [35]:
# Tensor(3차원 이상)
tensor = np.arange(1,25).reshape(2,3,4)
tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [36]:
vector.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [37]:
vector.size, matrix.size, tensor.size

(4, 6, 24)

In [38]:
# data type
# float32 : 32bit로 표시 - single precision
# float64 : 64bit로 표시 - double precision
a = np.array([1,2,3], dtype=np.float32)
b = np.array([1,2,3], dtype=np.float64)
c = np.array([1,2,3], dtype=np.int16)
d = np.array([1,2,3], dtype=np.int32)
a, b, c, d

(array([1., 2., 3.], dtype=float32),
 array([1., 2., 3.]),
 array([1, 2, 3], dtype=int16),
 array([1, 2, 3]))

##### reshape

In [39]:
matrix.shape

(2, 3)

In [40]:
matrix.reshape(6,), matrix.reshape(6,1), matrix.reshape(1,6)

(array([ 1,  2,  3,  4, 15,  6]),
 array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [15],
        [ 6]]),
 array([[ 1,  2,  3,  4, 15,  6]]))

In [41]:
matrix.reshape(3,2)

array([[ 1,  2],
       [ 3,  4],
       [15,  6]])

In [42]:
# -1은 numpy가 알아서 맞춰줌(단, size가 동일)
matrix.reshape(-1,)

array([ 1,  2,  3,  4, 15,  6])

In [43]:
matrix.reshape(2,-1), matrix.reshape(2,-1).shape

(array([[ 1,  2,  3],
        [ 4, 15,  6]]),
 (2, 3))

In [44]:
tensor, tensor.reshape(4,-1)

(array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]),
 array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]))

In [45]:
matrix.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [15],
       [ 6]])

### flatten

In [46]:
tensor.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [47]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

### 3. Indexing & Slicing

##### Indexing

In [48]:
matrix

array([[ 1,  2,  3],
       [ 4, 15,  6]])

In [51]:
matrix[0], matrix[0][1], matrix[0,1]

(array([1, 2, 3]), 2, 2)

In [52]:
tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [53]:
tensor[1][1][2], tensor[1,1,2]

(19, 19)

##### Slicing

In [54]:
b = np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
# 5,6,9,10
b[1:3, 1:3], b[1:3][1:3]

(array([[ 5,  6],
        [ 9, 10]]),
 array([[ 8,  9, 10, 11]]))

In [60]:
# 5,6,7,9,10,11
b[1:3, 1:], b[1:3][1:]

(array([[ 5,  6,  7],
        [ 9, 10, 11]]),
 array([[ 8,  9, 10, 11]]))

In [63]:
# x는 앞에 3열, y는 마지막 열
x = b[:, :-1]
y = b[:, -1]
x, y, x.shape, y.shape

(array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]),
 array([ 3,  7, 11, 15]),
 (4, 3),
 (4,))