### Numerical Python(Numpy) - Part1

In [43]:
# de facto standard (사실상의 표준)
import numpy as np

In [44]:
a = [1,2,3]
a * 3, a + a + a

([1, 2, 3, 1, 2, 3, 1, 2, 3], [1, 2, 3, 1, 2, 3, 1, 2, 3])

In [45]:
list(map(lambda x : 3 * x, a))

[3, 6, 9]

In [46]:
tuple(map(lambda y : y / 5, a))

(0.2, 0.4, 0.6)

In [47]:
b = np.array(a)
b * 3

array([3, 6, 9])

##### 1.Numpy Dimensional Array

In [48]:
c = np.array(a, float)
c

array([1., 2., 3.])

In [49]:
type(c)

numpy.ndarray

In [50]:
c.dtype, c.shape

(dtype('float64'), (3,))

##### 2. Array Shape

In [51]:
# Vector(1차원)
vector = np.array([1,4,5,8])
vector_2dm = vector.reshape(-1, 4)

print(vector, vector_2dm)
vector.shape, vector_2dm.shape

[1 4 5 8] [[1 4 5 8]]


((4,), (1, 4))

In [52]:
# Matrix(2차원)
matrix = np.array([[1, 2, 3], [4, 15, 6]])
matrix

array([[ 1,  2,  3],
       [ 4, 15,  6]])

In [53]:
# Tensor(3차원 이상)
tensor = np.arange(1,25).reshape(2,3,4)
tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [54]:
vector.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [55]:
vector.size, matrix.size, tensor.size

(4, 6, 24)

In [56]:
# data type
# float32 : 32bit로 표시 - single precision
# float64 : 64bit로 표시 - double precision
a = np.array([1,2,3], dtype=np.float32)
b = np.array([1,2,3], dtype=np.float64)
c = np.array([1,2,3], dtype=np.int16)
d = np.array([1,2,3], dtype=np.int32)
a, b, c, d

(array([1., 2., 3.], dtype=float32),
 array([1., 2., 3.]),
 array([1, 2, 3], dtype=int16),
 array([1, 2, 3]))

##### reshape

In [57]:
matrix.shape

(2, 3)

In [58]:
matrix.reshape(6,), matrix.reshape(6,1), matrix.reshape(1,6)

(array([ 1,  2,  3,  4, 15,  6]),
 array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [15],
        [ 6]]),
 array([[ 1,  2,  3,  4, 15,  6]]))

In [59]:
matrix.reshape(3,2)

array([[ 1,  2],
       [ 3,  4],
       [15,  6]])

In [60]:
# -1은 numpy가 알아서 맞춰줌(단, size가 동일)
matrix.reshape(-1,)

array([ 1,  2,  3,  4, 15,  6])

In [61]:
matrix.reshape(2,-1), matrix.reshape(2,-1).shape

(array([[ 1,  2,  3],
        [ 4, 15,  6]]),
 (2, 3))

In [62]:
tensor, tensor.reshape(4,-1)

(array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]),
 array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]))

In [63]:
matrix.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [15],
       [ 6]])

### flatten

In [64]:
tensor.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [65]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])