### Numerical Python(Numpy) - Part1

In [41]:
# de facto standard (사실상의 표준)
import numpy as np

In [42]:
a = [1,2,3]
a * 3, a + a

([1, 2, 3, 1, 2, 3, 1, 2, 3], [1, 2, 3, 1, 2, 3])

In [43]:
list(map(lambda x : 3 * x, a))

[3, 6, 9]

In [44]:
b = np.array(a)
b * 3

array([3, 6, 9])

##### 1.Numpy Dimensional Array

In [45]:
c = np.array(a, float)
c

array([1., 2., 3.])

In [46]:
type(c)

numpy.ndarray

In [47]:
c.dtype, c.shape

(dtype('float64'), (3,))

##### 2. Array Shape

In [48]:
# Vector(1차원)
vector = np.array([1,4,5,8])
vector.shape

(4,)

In [49]:
# Matrix(2차원)
matrix = np.array([[1, 2, 3], [4, 15, 6]])
matrix

array([[ 1,  2,  3],
       [ 4, 15,  6]])

In [51]:
# Tensor(3차원 이상)
tensor = np.arange(1,25).reshape(2,3,4)
tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [52]:
vector.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [53]:
vector.size, matrix.size, tensor.size

(4, 6, 24)

In [57]:
# data type
# float32 : 32bit로 표시 - single precision
# float64 : 64bit로 표시 - double precision
a = np.array([1,2,3], dtype=np.float32)
b = np.array([1,2,3], dtype=np.float64)
c = np.array([1,2,3], dtype=np.int16)
d = np.array([1,2,3], dtype=np.int32)
a, b, c, d

(array([1., 2., 3.], dtype=float32),
 array([1., 2., 3.]),
 array([1, 2, 3], dtype=int16),
 array([1, 2, 3]))